Feature/test python wf
ASAP-CRN/harmonized-wf-dev pull request #34
Opened 2024-02-21 14:33 UTC by kfang4

Tested re-written ASAP workflow (R -> Python) with two samples from three teams each. Outputs and file names were inspected and changes have been made to reflect that.

2024-02-21 15:07 UTC, hkeward requested changes
A few small changes, overall looks great!

2024-02-21 15:07 UTC, hkeward commented on workflows/cohort_analysis/cluster_data/cluster_data.wdl
> +		# TODO - script doesn't use cell_type_markers_list (incomplete)
Does it now or is this still a TODO?

2024-02-21 15:10 UTC, kfang4 commented on workflows/cohort_analysis/cohort_analysis.wdl
> +		mv "plots/violin_n_genes_by_counts.png" "plots/~{cohort_id}.n_genes_by_counts.violin.png"
Unfortunately, scanpy always prepends- for example, with "violin" or "umap" (issue: https://github.com/scverse/scanpy/issues/1508).

2024-02-21 15:14 UTC, kfang4 commented on workflows/main.wdl
>  		Array[Array[File]] log = preprocess.log
I followed the same format as cellranger and prefixed outputs with `cellbender_`, [here](https://github.com/ASAP-CRN/harmonized-wf-dev/blob/c7200305530a671cfbd39c7b6e1c3448407f3554/workflows/preprocess/preprocess.wdl#L51-L59)

2024-02-21 15:39 UTC, hkeward commented on workflows/main.wdl
>  		Array[Array[File]] log = preprocess.log
I'd prefer if at least in main.wdl the `log` output was called `cellbender_log`. counts files are less ambiguous than `log` but could potentially still do with prefixing. `report_html`, `adata_object`, a bunch of other preprocessing outputs could also hypothetically come from a couple different steps -- I think adding prefixes at least to main.wdl outputs, but also ideally to preprocessing outputs, would help with ambiguity.

I am imagining the eventual workbench interface with outputs, where we'll just get an output called `harmonized_pmdbs_analysis.log` (not the surrounding comments that say it comes from preprocess) -- I don't want whoever is inspecting this to need to refer to the workflow definition to figure out what this `log` refers to.

2024-03-11 16:28 UTC, hkeward approved these changes

2024-03-11 16:40 UTC, merged